language: node_js

node_js: node

git:
  depth: false

cache: npm

install:
  - npm ci

script:
  - npm run build

branches:
  only:
    - gh-pages
    - /.*/

deploy:
  provider: pages
  skip-cleanup: true
  on:
    branch: gh-pages
