language: node_js

node_js: node

git:
  depth: false

cache: npm

install:
  - npm ci

script:
  - npm run build

#branches:
#only:
#- master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  keep_history: true
  on:
    branch: master
